### ISSUE TITLE
error: addresses not defined

### ISSUE THREAD

**Issue by jamesdixon** [scravy/uuid-1345#2]
Hi,

Just tried to load this up and when I start my server, I see the following error:

```
/Users/jamesdixon/Projects/scout/platform/api/node_modules/macaddress/index.js:34
        addresses = {};
                  ^

ReferenceError: addresses is not defined
    at /Users/jamesdixon/Projects/scout/platform/api/node_modules/macaddress/index.js:34:19
    at Array.forEach (native)
    at Object.lib.networkInterfaces (/Users/jamesdixon/Projects/scout/platform/api/node_modules/macaddress/index.js:33:25)
    at Object.lib.one (/Users/jamesdixon/Projects/scout/platform/api/node_modules/macaddress/index.js:79:26)
    at Object.<anonymous> (/Users/jamesdixon/Projects/scout/platform/api/node_modules/uuid-1345/index.js:58:23)
```

Is there something I need to do to make this function?

Thanks,
James

**Comment by jamesdixon** [comment]
@scravy just wondering if you had any idea what might be causing this? Thanks!

**Comment by scravy** [comment]
@jamesdixon Which version of node are you using?

Ultimately this is an issue with the macaddress package (which I built though ;-). V1-UUIDs require the mac address and apparently something has gone wrong here.

**Comment by jamesdixon** [comment]
@scravy I gave it a go on v5.11.0. Let me know if I can be of assistance!

**Comment by scravy** [comment]
The macaddress package was needed in the past as node did not give that information by itself. I believe since v4.0.0 and iojs macaddress is available natively which means the macaddress package is probably not needed at all.

I will in the weekend write a little patch to only load the mac address package if the information is not already present. Would be great if you could check that out then!

**Comment by jamesdixon** [comment]
Thanks for looking into it 👍  Let me know when you need me to test

**Comment by jamesdixon** [comment]
hi @scravy - just wondering if you had a chance to look at this?

thanks!

**Comment by jamesdixon** [comment]
hi again. sorry to be a pest, but was just curious if you had any time to take a look at this? Also just tried on Node 6.1 and still seeing the same error.

**Comment by scravy** [comment]
The current version `1.0.2` references a more recent version of `macaddress` which is almost a complete rewrite.
