### ISSUE TITLE
Why have a callback api when work is done synchronously anyway?

### ISSUE THREAD

**Issue by LinusU** [scravy/uuid-1345#4]
https://github.com/scravy/uuid-1345/blob/master/index.js#L322-L328

Everything in this library is synchronously so it doesn't make any sense to have a callback based API. It gives the consumer a false sense that the work is being done in the thread-pool when in reality it isn't...

**Comment by scravy** [comment]
For version 1 uuids an async call to get the mac address is being made.

Also this offers the possibility to later change the implementation (granted that never happened) to for example access a different random source.
